### ISSUE TITLE
Error in deployment

### ISSUE THREAD

**Issue by rudnypc** [bitnami/bitnami-docker-harbor-registryctl#1]
**Description**
When I try to deploy the registryctl, I receive a error.

**Steps to reproduce the issue:**

1. try to deploy the bitnami image of registryctl v2

**Describe the results you received:**
18:30:42.66 
 18:30:42.66 Welcome to the Bitnami harbor-registryctl container
 18:30:42.66 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-harbor-registryctl
 18:30:42.66 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-harbor-registryctl/issues
 18:30:42.67 
 18:30:42.67 INFO  ==> ** Starting Harbor Registryctl setup **
 18:30:42.70 INFO  ==> Validating Harbor Registryctl settings...
18:30:42.82 INFO  ==> No custom certificates were installed in the system
 18:30:42.83 INFO  ==> ** Harbor Registryctl setup finished! **
 18:30:42.86 INFO  ==> ** Starting Harbor Registryctl **
2020-10-08T18:30:43Z [ERROR] [/registryctl/config/config.go:63]: failed to load storage driver, err:open : no such file or directory
2020-10-08T18:30:43Z [FATAL] [/registryctl/main.go:78]: Failed to load configurations with error: open : no such file or directory

**Describe the results you expected:**
Running status

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**
2
- Output of `docker version`:

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056dbc
 Built:             Thu Apr 11 04:44:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 39
 Running: 26
 Paused: 0
 Stopped: 13
Images: 42
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: 5ke6lltd01bbhhq4eq9kk0pfz
 Is Manager: true
 ClusterID: bogtbb4r2sc5gbw8avm60prf7
 Managers: 8
 Nodes: 8
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 10.83.0.44
 Manager Addresses:
  10.83.0.250:2377
  10.83.0.43:2377
  10.83.0.44:2377
  10.83.0.45:2377
  10.83.0.46:2377
  10.83.0.47:2377
  10.83.0.48:2377
  10.83.0.49:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.66GiB
Name: SRV-SWARM-01
ID: 2PFR:6QWT:QI5A:3TSD:JZST:WKNF:Y6JH:GY2B:Z5LN:DU45:CK6L:6MJS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Virtual machine in vmware

**Comment by Caesar2011** [comment]
I get the same error message. Using the latest version of the bitnami container.

**Comment by rudnypc** [comment]
I changed registryctl/config.yml to :
```
---
version: 0.1
protocol: "http"
port: 8080
log_level: "INFO"
registry_config: "/etc/registry/config.yml"

```
https://github.com/bitnami/bitnami-docker-harbor-registryctl/blob/master/2/debian-10/config/registryctl/config.yml

Works fine now.

**Comment by Caesar2011** [comment]
> 
> 
> I changed registryctl/config.yml to :
> 
> ```
> ---
> version: 0.1
> protocol: "http"
> port: 8080
> log_level: "INFO"
> registry_config: "/etc/registry/config.yml"
> ```
> 
> https://github.com/bitnami/bitnami-docker-harbor-registryctl/blob/master/2/debian-10/config/registryctl/config.yml
> 
> Works fine now.

It worked. This repository should be updated.

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting. While it's true that these containers are expected to be used with the Bitnami Harbor chart, I believe it should work without issues when using the standalone docker-compose files. We will work on changing it. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
